
#  /$$$$$$$$/$$$$$$$   /$$$$$$  /$$       /$$              /$$$$$$  /$$   /$$ /$$$$$$
#    | $$__/ $$__  $$ /$$__  $$| $$      | $$             /$$__  $$| $$  | $$|_  $$_/
#    | $$  | $$  \ $$| $$  \ $$| $$      | $$            | $$  \__/| $$  | $$  | $$
#    | $$  | $$$$$$$/| $$  | $$| $$      | $$            | $$ /$$$$| $$  | $$  | $$
#    | $$  | $$__  $$| $$  | $$| $$      | $$            | $$|_  $$| $$  | $$  | $$
#    | $$  | $$  \ $$| $$  | $$| $$      | $$            | $$  \ $$| $$  | $$  | $$
#    | $$  | $$  | $$|  $$$$$$/| $$$$$$$$| $$$$$$$$      |  $$$$$$/|  $$$$$$/ /$$$$$$
#    |__/  |__/  |__/ \______/ |________/|________/       \______/  \______/ |______/


Variables:
  prefix: '&9&lMS3 &8| &7'
  enableSneakRightClickSelection: false # Allows shift right-clicking a player to open the troll menu.
  advancedPermission:
    # Basically, this is a check that doesn't have to check if the player has the permission 'ms3.use'
    # It checks if the player name has the name then it allows it. Useful if you want to limit the TrollGUI just for you.
    name: 'Steve' # If your server is in offline mode then the player must join before
    enabled: false
  # Used for the commands names (e.g. /troll)
  # Note: Try not to use commands that are already used this will cause either errors or just use the plugin that loads firstly
  # Note: If the name is invalid it will fallback to "ms3"
  commands:
    troll:
      name: 'ms3'
      # Used for additional command names that do the same thing
      alias:
        enabled: false
        aliases:
          - 'mysystem3'


MenuTitles:
  trollGUI: '&8x &9&lMS3&8 - &7%VICTIM% &8x' # Possible placeholders: %PLAYER% - Player that opened the menu, %VICTIM% - The player that is being trolled.
  selectPlayer: '&8x &9Select a player &8x'
  settings: '&8x &9Select settings &8x'

Messages:
  missingPermissionsMessage: true
  missingPermissions: '&cYou''re missing the permissions "ms3.use"'
  reloaded: '&cReloaded the configuration successfully.'
  noItemInHand: '&7Player &b%PLAYER%&7 isn''t holding an item in their hand.'
  alreadyOnFirstPage: '&cYou are already on the first page.'
  alreadyOnLastPage: '&cYou are already on the last page.'
  playerNotAvaliable: '&cPlayer either disconnected or is not available'

MenuItems:
  trollMenu:
      burnPlayer:
        name: '&6Burn the player'
        lore: '&7Summon Ragnarok the god of fire to punish him!'
        options:
          burnTime: 7 # x seconds until the player stops burning.
      closeGUI:
        name: '&cClose inventory'
        lore: '&7Closes the inventory (or any GUI) the player has open'
      dropAll:
        name: '&8Drop all items from Player'
        lore: '&7"Who tf did cut a hole in my pants?!"'
      dropItem:
        name: '&8Drop the item from players hand'
        lore: '&7Makes the hand from the player slippy'
      explodePlayer:
        name: '&4Explode the player'
        lore: '&7Do you also smell gunpowder?'
        options:
          explodeRadius: 1 # The radius of the explosion. (Please keep this value LOW! High values can easily crash the server usually anything > 200 crashes)
          explodeRandomness: true # Uses the value above as the highest value and 1 as the lowest value, Exploding radius is somewhere between 1 and explodeRadius.
      fakeBlock:
        name: '&eFake Blocks (Clientside)'
        lore: '&7"HEY SOMEONES IS GRIEFING!" you hear them shout'
        options:
          block: 'TNT' # Use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html as a reference. (If the custom block is invalid TNT will be the default)
          radius: 5 # Same as explodeRadius, Keep this LOW! High values tend to either crash the server OR that the player gets disconnected due to a timeout.
      fakeClear:
        name: '&eFake clear players inventory'
        lore: '&7Wipes the player inventory then after %TIME% seconds restores it'
        options:
          fakeClearDelay: 10 # x seconds until all items return to the inventory.
      fakeOperator:
        name: '&bFake OP / DEOP The player'
        lore: '&7If player has OP then it will send the deop message and if not the operator message'
      freezePlayer:
        name: '&bFreeze Player'
        lore: '&7Make the player AFK involuntary'
      invSee:
        name: '&9See the inventory from the player'
        lore: '&7HAVE YOU STOLE MY DIAMONDS?!!'
      invShare:
        name: '&9Open inventory to everyone'
        lore: '&7"Ohh... What''s that?"'
      launchPlayer:
        name: '&6Launch Player'
        lore: '&7Let the player touch the sky'
      noBreak:
        name: '&7No Break'
        lore: '&7Disables the breaking ability of the player'
      noBuild:
        name: '&7No Build'
        lore: '&7Disables the building ability of the player'
      randomLook:
        name: '&cRandom look'
        lore: '&7Makes the player look in random locations'
        options:
          randomLookTime: 10 # x seconds until the player stops the random looking
      reverseMessage:
        name: '&9Reverse send message'
        lore: '&7Do you are have a stroke'
      returnToPlayerSelector:
        name: '&cGo Back'
        lore: '&7Return to the Player Selector'
      scarePlayer:
        name: '&5Scare Player'
        lore: '&7Spooky Scary Skeletons'
      thunder:
        name: '&3Thor / Strike Player'
        lore: '&7Truly godlike powers!'
      extras:
        isEnabled: '&8> &a✓ &8- Enabled.'
        isDisabled: '&8> &c✕ &8- Disabled.'
  settingsMenu:
    reload:
      name: '&cReload the current configuration.'
      lore: '&7Reload the current config, Without needing to reload the server. (Note: If you change command names you MUST reload the server to make them work)'
  playerSelector:
    close:
      name: '&cCLOSE'
      lore: '&7Close this menu'
    left:
      name: '&8← &7BACK'
      lore: '&7Go one back'
    right:
      name: '&7NEXT &8→'
      lore: '&7Go to the next page'
    extras:
      hasOP: '&7This player is &coperator&7.'